### ISSUE TITLE
Inconsolata patched font does not work on Mac OS X/iTerm 2

### ISSUE THREAD

**Issue by RageZBla** [ryanoasis/nerd-filetype-glyphs-fonts-patcher#13]
I tried both Mono and double width without any success.

**Comment by ryanoasis** [comment]
@RageZBla Do you have any more details? Does not work as in you cannot see any of the added glyphs or the powerline symbols?

Are you using `Inconsolata for Powerline Plus Nerd File Types.otf` or `Inconsolata for Powerline Plus Nerd File Types Mono.otf` ?

**Comment by RageZBla** [comment]
@ryanoasis I can see the powerlines ghyphs but not the added one. Yes I am sure I am using the right font, I couldn't get it working with both fonts.

**Comment by ryanoasis** [comment]
@RageZBla 

* can you provide a screenshot?
* do any of the patched fonts besides Inconsolata work?

Unfortunately I cannot test this because I currently do not have access to OS X

**Comment by RageZBla** [comment]
@ryanoasis 

[Inconsolata](http://i.imgur.com/qmSZIVh.png)
[test in terminal](http://i.imgur.com/YB2roB0.png)
[iTerm2 font settings](http://i.imgur.com/bNKgKEY.png)
[Droid Sans screenshot](http://i.imgur.com/ToMe3uM.png)

Just tried Droid now same result, not sure what's the problem since the same font works on Linux.

**Comment by RageZBla** [comment]
Also just tried in macvim, now it works, it seems it just don't work in iTerm

**Comment by RageZBla** [comment]
Ok my bad, in the iTerm settings dialog there is a separate settings for non-ASCII font. Changing that fixed it! 

Sorry the false report.

**Comment by RageZBla** [comment]
And thanks for your great work! :+1:

**Comment by ryanoasis** [comment]
@RageZBla hey no problem. Thank you for the details. I think I will **at least** add a note about non-ASCII and/or iTerm in the docs (either here or on https://github.com/ryanoasis/vim-webdevicons)

:question: If you have it working on Mac OS X maybe I could ask you if you could submit or post a screenshot showing the glyphs? 
I would like to add it to the readme (for ryanoasis/vim-webdevicons/issues/32)

**Comment by RageZBla** [comment]
Sure, I was not sure exactly what kind of screenshot you need, here a really basic one. 

![Imgur](http://i.imgur.com/8d3RaSJ.png?1)

You can poke me if you want some more.

**Comment by RageZBla** [comment]
One more the previous one had some artefacts.

![Imgur](http://i.imgur.com/2epIvPx.png)

**Comment by ryanoasis** [comment]
@RageZBla Thanks a lot! I will give you the proper attribution in the next bugfix/patch release (v0.4.4 on https://github.com/ryanoasis/vim-webdevicons)

tmux FTW :wink:

**Comment by xavierartot** [comment]
Hi,
I don't understood?
```Ok my bad, in the iTerm settings dialog there is a separate settings for non-ASCII font. Changing that fixed it!
```
you mean don't use ASCII?

**Comment by rahmatawaludin** [comment]
This one should be added to doc. I also using iTerm2 and the custom font only work when I set "Non-ASCII Font" settings. Easy to miss that.. ;)

**Comment by ryanoasis** [comment]
@rahmatawaludin Yes you are correct it really should be in the readme and/or FAQ. 

I am a bit busy right now to do it myself but you can give a go if you want to contribute.

Feel free to submit a PR or add it to the [wiki FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ).

Which reminds me I really need to add some info on contributing! :+1:

**Comment by aslijiasheng** [comment]
@RageZBla  hello I encountered the same problem  , Will you solve it?

**Comment by RageZBla** [comment]
@aslijiasheng changing the `Non-ASCII Font` settings fixed it for me.

**Comment by aslijiasheng** [comment]
I changing the ``` Non-ASCII Font```, but problem still show  
![image](https://cloud.githubusercontent.com/assets/6622275/16070525/b703a7c0-3308-11e6-85c3-0883ea6ea619.png)

**Comment by aslijiasheng** [comment]
![image](https://cloud.githubusercontent.com/assets/6622275/16070534/c49f99b6-3308-11e6-8828-1fa35f46cb24.png)

**Comment by aslijiasheng** [comment]
@RageZBla abvoe my vimrc and iterm config, Have it problem?

**Comment by RageZBla** [comment]
@aslijiasheng your screenshot is showing the custom icons so not sure what problem you are having?

**Comment by aslijiasheng** [comment]
@RageZBla I use web-devicon after vim index.php for example:

**Comment by aslijiasheng** [comment]
![image](https://cloud.githubusercontent.com/assets/6622275/16070732/0f4ed174-330a-11e6-9e7d-1e843a73ef10.png)

**Comment by RageZBla** [comment]
@aslijiasheng thanks for explaining, did you try different font or font size, I think some patched fonts don't work well with small font size

**Comment by aslijiasheng** [comment]
@RageZBla I use powerline sauce and many more font or font size, but this problem still show it。  this is fix?

**Comment by RageZBla** [comment]
@ryanoasis any ideas about that one?

**Comment by ryanoasis** [comment]
My gut is saying to look into `listchars`

I will try to give more help once I reach my pc

**Comment by ryanoasis** [comment]
@aslijiasheng 

File encoding looks correct (because you can see the glyphs)

If you can, could you link to your `vimrc` or provide minimum configuration where this problem can be replicated?

If you can visually select the 'defect chars' this could help figure out whats going on: http://vim.wikia.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor

I have that command mapped, to `<leader>zz` for example

--

If you could provide the output of:

`:set fillchars?`
`:set listchars?`

**Comment by aslijiasheng** [comment]
ok, I execute ``` :set fillchars?``` show 
![image](https://cloud.githubusercontent.com/assets/6622275/16101629/3c82a34c-339a-11e6-8508-b3104be03e5f.png)
and ``` :set listchars?``` show
![image](https://cloud.githubusercontent.com/assets/6622275/16101641/4f187d38-339a-11e6-84e7-7bbb251990df.png)
My vimrc about vim-devicons for example :
```
"webdevicons图标
if exists("g:loaded_webdevicons")
    call webdevicons#refresh()
endif
let g:airline_powerline_fonts = 1
let g:webdevicons_enable = 1
let g:webdevicons_enable_nerdtree = 1
let g:webdevicons_enable_unite = 1
let g:webdevicons_enable_vimfiler = 0
let g:webdevicons_enable_airline_tabline = 1
let g:webdevicons_enable_airline_statusline = 1
let g:webdevicons_enable_ctrlp = 0
let g:webdevicons_enable_flagship_statusline = 0
let g:WebDevIconsUnicodeDecorateFileNodes = 0
```
this is my vimrc complete config https://github.com/aslijiasheng/jacksonvimrc/blob/master/vimrc/jackson/plugin.vim

**Comment by sureshsaragadam** [comment]
Install nerd-fonts

https://github.com/ryanoasis/nerd-fonts
git clone https://github.com/ryanoasis/nerd-fonts.git
cd nerd-fonts
./install.sh
reboot

**Comment by jonahfang** [comment]
@sureshsaragadam Thanks, it works!
