### ISSUE TITLE
Indent Line plugin

### ISSUE THREAD

**Issue by aliev** [ryanoasis/nerd-filetype-glyphs-fonts-patcher#2]
can also add fonts that (for patched fonts) https://github.com/Yggdroot/indentLine#font-patching ?

**Comment by ryanoasis** [comment]
That's interesting thanks. Should be possible to add to the patcher but I'll have to look into it

**Comment by ryanoasis** [comment]
**update:** I did add this glyph to the branch i'm currently working on (not quiter ready for master). So far seems to be working well

**Comment by ryanoasis** [comment]
working now as of: 6c6ef8ef0ca382efbd39bd709007e6ee8f64edbf
