### ISSUE TITLE
patch fixed/mono/non-variable fonts correctly (will fix certain terminal emulators)

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/nerd-filetype-glyphs-fonts-patcher#4]
Fonts that are mono before patching should remain so after patching

terminals where the issue is apparent (not comprehensive):
- urxvt
- gnome terminal

issue links:
- ryanoasis/vim-webdevicons#11
- ryanoasis/vim-webdevicons#21

**Comment by ryanoasis** [comment]
![selection_15_02_15_17 22 11_1160x736_001](https://cloud.githubusercontent.com/assets/8083459/6205330/63451b90-b538-11e4-9b5e-11f4d5c3afc8.png)

**Comment by ryanoasis** [comment]
working now as of: 6c6ef8ef0ca382efbd39bd709007e6ee8f64edbf

**Comment by blueyed** [comment]
@ryanoasis 
Thanks!  I'm looking forward to trying it.

I've noticed that there is "Mono" now twice in the font names, e.g. "Ubuntu Mono Plus Nerd File Types Mono"; maybe instead of the second "Mono" it should be "Single" - resulting in "Ubuntu Mono Plus Nerd File Types Single"?!

**Comment by ryanoasis** [comment]
@blueyed yeah that is something I was aware of but I guess I thought of it in this context: original font + glyphs (patched). If the original font was mono I was just concatenating 'Plus Nerd File Types' and since it then ended up no longer being mono I thought I would append 'mono' to the "patched" part. 

You make a good point though and I will definitely think about a better naming convention.

Thanks I would love any feedback you have. I think you will find the single width glyphs some are very hard to distinguish but I wanted to put this out on master branches because it felt solid enough and I thought it is never going to be perfect so it made no sense for me to keep holding it back in topic bracnches.
