### ISSUE TITLE
Licensing compliance

### ISSUE THREAD

**Issue by abl** [ryanoasis/nerd-filetype-glyphs-fonts-patcher#7]
Hi! It looks like you're distributing modified fonts. Some of them have licensing requirements that appear to not be met. A (non-exhaustive) list follows.

Anonymous (renamed to Anonymice?):
OFL - a copy of the copyright+license has to be included with all distributions. Modifications/originals must be released under the OFL.
http://www.marksimonson.com/fonts/view/anonymous-pro
http://scripts.sil.org/cms/scripts/page.php?item_id=OFL-FAQ_web

Droid Sans:
Apache v2.0 - a copy of the copyright+license has to be included with all distributions.
http://www.google.com/fonts/specimen/Droid+Sans
https://www.apache.org/licenses/LICENSE-2.0.html

Liberation (renamed to Literation?):
I'm assuming you've got a recent version, which would be under the OFL - old versions are under the GPL.
OFL - a copy of the copyright+license has to be included with all distributions. Modifications/originals must be released under the OFL.
https://fedorahosted.org/liberation-fonts/
http://scripts.sil.org/cms/scripts/page.php?item_id=OFL-FAQ_web

PragmataPro:
PragmataPro is not free software and the author hasn't ever made it available in a particularly permissive form. Also worth noting - you appear to have an older (buggy) version of PragmataPro which is missing certain ligatures added in 0.820.
http://www.fsd.it/fonts/pragmatapro.htm
http://www.fsd.it/fonts/eula.htm

Proggy:
Appears to be public domain?
http://upperbounds.net/

Source Code (renamed to Sauce Code?):
OFL - a copy of the copyright+license has to be included with all distributions. Modifications/originals must be released under the OFL.
https://github.com/adobe-fonts/source-code-pro
https://github.com/adobe-fonts/source-code-pro/blob/master/LICENSE.txt

Ubuntu Mono:
UFL - fonts and derivatives may only be redistributed under the UFL.
http://font.ubuntu.com/licence/

**Comment by ryanoasis** [comment]
Thanks for this. I will try to get this fixed soon

**Comment by ryanoasis** [comment]
@abl I believe I have corrected these issues. Please have a look, I would appreciate some feedback.

I will give you some time to respond but I will close this issue if no response.

Thanks

**Comment by ryanoasis** [comment]
completed and updated in master. officially linked to v0.2.1 upcoming

**Comment by abl** [comment]
Looks great, thanks!

**Comment by ryanoasis** [comment]
@abl No probem. Thank you. I will try to be more vigilant with future fonts

**Comment by ryanoasis** [comment]
@Vaelatern As far as I understand it doesn't as all the code used to patch the fonts is licensed under MIT and each fonts license is provided per each font's relevant folder.

Most of the fonts are licensed under the SIL Open Font License which allows the fonts to be used, modified, and distributed. The main compliance issue we had before was the reserved font name and original license not being included.

Okay I found this which is not exactly the same thing:
> The requirement for fonts to remain under this license does not apply to any document created using the fonts or their derivatives.

Can I ask the reason for your question?

**Comment by Vaelatern** [comment]
There is an attempt to package these for [Void Linux](https://voidlinux.eu), and we would like to make sure we don't make a mistake with the license and its terms (such as making sure the relevnt licenses get in to the final product).

**Comment by ryanoasis** [comment]
@Vaelatern Ah okay. Well we have to confirm licenses again. Relevant issue #266

**Comment by ryanoasis** [comment]
FYI the project LICENSE itself has also recently been updated. I'm no expert and it's a bit complicated but basically there are many differing licensed source files in this repo so overall this project is no longer licensed under MIT (though individual source files are).
